trigger: ["master"]
pr: ["master"]

resources:
  repositories:
    - repository: templates
      type: github
      name: alecmocatta/azure-pipeline-templates
      endpoint: alecmocatta

jobs:
- template: rust.yml@templates
  parameters:
    endpoint: alecmocatta
    default:
      rust_toolchain: stable nightly
      rust_lint_toolchain: nightly-2020-04-30
      rust_flags: ''
      rust_features: ''
      rust_target_check: ''
      rust_target_build: ''
      rust_target_run: ''
    matrix:
      windows:
        imageName: 'windows-latest'
        rust_target_run: 'x86_64-pc-windows-msvc i686-pc-windows-msvc' # currently broken building crate-type=lib: x86_64-pc-windows-gnu i686-pc-windows-gnu
      mac:
        imageName: 'macos-latest'
        rust_target_run: 'x86_64-apple-darwin'
      linux:
        imageName: 'ubuntu-latest'
        rust_target_run: 'x86_64-unknown-linux-gnu i686-unknown-linux-gnu' # failing due to openssl not being built with musl-gcc; vendoring would solve this but slows ci: x86_64-unknown-linux-musl i686-unknown-linux-musl
